### ISSUE TITLE
Add registration new fields

### ISSUE THREAD

**Issue by SirAlyon** [SirAlyon/deliveboo#8]
1. Add needed new inputs in user view auth/register.blade.php.
2. Overwrite showRegistrationForm in auth/RegisterController.php
3. Edit User model, update validation and ::create methods for new fields.
4. Use Type model for multiselect values.
5. Server-side validation for new fields data.
6. Test everythinh

**Comment by Alexxboc** [comment]
Prendo in carico questa issue, andrò anche a creare e modificare i layout da estendere di admin
